//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koinzer.pcdddfinwpf {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Koinzer.pcdddfinwpf.Strings", typeof(Strings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to About.
		/// </summary>
		public static string About {
			get {
				return ResourceManager.GetString("About", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Contributing.
		/// </summary>
		public static string AboutBox_Contributing {
			get {
				return ResourceManager.GetString("AboutBox.Contributing", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Contributing, reporting errors.
		/// </summary>
		public static string AboutBox_ContributingHeader {
			get {
				return ResourceManager.GetString("AboutBox.ContributingHeader", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Fork me on.
		/// </summary>
		public static string AboutBox_ForkMeOn {
			get {
				return ResourceManager.GetString("AboutBox.ForkMeOn", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GitHub.
		/// </summary>
		public static string AboutBox_GitHub {
			get {
				return ResourceManager.GetString("AboutBox.GitHub", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GitHub Issues Page.
		/// </summary>
		public static string AboutBox_GitHubIssuesPage {
			get {
				return ResourceManager.GetString("AboutBox.GitHubIssuesPage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Libraries.
		/// </summary>
		public static string AboutBox_Libraries {
			get {
				return ResourceManager.GetString("AboutBox.Libraries", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to License.
		/// </summary>
		public static string AboutBox_License {
			get {
				return ResourceManager.GetString("AboutBox.License", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please report any issues on the.
		/// </summary>
		public static string AboutBox_PleaseReportAnyIssuesOnThe {
			get {
				return ResourceManager.GetString("AboutBox.PleaseReportAnyIssuesOnThe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Reporting errors and feature requests.
		/// </summary>
		public static string AboutBox_ReportingErrors {
			get {
				return ResourceManager.GetString("AboutBox.ReportingErrors", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Translating.
		/// </summary>
		public static string AboutBox_Translating {
			get {
				return ResourceManager.GetString("AboutBox.Translating", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to If you would like to translate this program to another language or correct any errors, contact me via email..
		/// </summary>
		public static string AboutBox_TranslatingText {
			get {
				return ResourceManager.GetString("AboutBox.TranslatingText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Channel.
		/// </summary>
		public static string AddChannel {
			get {
				return ResourceManager.GetString("AddChannel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Item.
		/// </summary>
		public static string AddItem {
			get {
				return ResourceManager.GetString("AddItem", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Range.
		/// </summary>
		public static string AddRange {
			get {
				return ResourceManager.GetString("AddRange", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to All Files.
		/// </summary>
		public static string AllFiles {
			get {
				return ResourceManager.GetString("AllFiles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Amber.
		/// </summary>
		public static string Amber {
			get {
				return ResourceManager.GetString("Amber", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Author.
		/// </summary>
		public static string Author {
			get {
				return ResourceManager.GetString("Author", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Caption.
		/// </summary>
		public static string Caption {
			get {
				return ResourceManager.GetString("Caption", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Channel.
		/// </summary>
		public static string Channel {
			get {
				return ResourceManager.GetString("Channel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Channels.
		/// </summary>
		public static string Channels {
			get {
				return ResourceManager.GetString("Channels", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Channel type.
		/// </summary>
		public static string ChannelType {
			get {
				return ResourceManager.GetString("ChannelType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Checked.
		/// </summary>
		public static string Checked {
			get {
				return ResourceManager.GetString("Checked", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Color.
		/// </summary>
		public static string Color {
			get {
				return ResourceManager.GetString("Color", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Control.
		/// </summary>
		public static string Control {
			get {
				return ResourceManager.GetString("Control", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		public static string Description {
			get {
				return ResourceManager.GetString("Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Device.
		/// </summary>
		public static string Device {
			get {
				return ResourceManager.GetString("Device", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Amber factor green.
		/// </summary>
		public static string DeviceAmberEditor_AmberGFactor {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.AmberGFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Amber factor red.
		/// </summary>
		public static string DeviceAmberEditor_AmberRFactor {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.AmberRFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Compensate blue.
		/// </summary>
		public static string DeviceAmberEditor_CompensateB {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.CompensateB", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Compensate red/green.
		/// </summary>
		public static string DeviceAmberEditor_CompensateRG {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.CompensateRG", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Use amber mixing.
		/// </summary>
		public static string DeviceAmberEditor_UseAmbermixing {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.UseAmbermixing", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Dimmer.
		/// </summary>
		public static string Dimmer {
			get {
				return ResourceManager.GetString("Dimmer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Down.
		/// </summary>
		public static string Down {
			get {
				return ResourceManager.GetString("Down", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Dropdown.
		/// </summary>
		public static string Dropdown {
			get {
				return ResourceManager.GetString("Dropdown", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error information.
		/// </summary>
		public static string ExceptionWindow_ExceptionTextHeader {
			get {
				return ResourceManager.GetString("ExceptionWindow.ExceptionTextHeader", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to A program error occurred. Please report errors to the developer, you can copy the text below. More information on the &quot;About&quot; page..
		/// </summary>
		public static string ExceptionWindow_Message {
			get {
				return ResourceManager.GetString("ExceptionWindow.Message", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Application error.
		/// </summary>
		public static string ExceptionWindow_MessageHeader {
			get {
				return ResourceManager.GetString("ExceptionWindow.MessageHeader", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Fade.
		/// </summary>
		public static string Fade {
			get {
				return ResourceManager.GetString("Fade", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Fade time [ms].
		/// </summary>
		public static string FadeTimeMs {
			get {
				return ResourceManager.GetString("FadeTimeMs", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Features.
		/// </summary>
		public static string Features {
			get {
				return ResourceManager.GetString("Features", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This feature is not a range feature and can only be applied to items..
		/// </summary>
		public static string FeatureSelector_FeatureRangeErrorText {
			get {
				return ResourceManager.GetString("FeatureSelector.FeatureRangeErrorText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error adding feature.
		/// </summary>
		public static string FeatureSelector_FeatureRangeErrorTitle {
			get {
				return ResourceManager.GetString("FeatureSelector.FeatureRangeErrorTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to File could not be loaded..
		/// </summary>
		public static string FileCouldNotBeLoaded {
			get {
				return ResourceManager.GetString("FileCouldNotBeLoaded", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to File could not be saved..
		/// </summary>
		public static string FileCouldNotBeSaved {
			get {
				return ResourceManager.GetString("FileCouldNotBeSaved", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Gobo 1 Rotation.
		/// </summary>
		public static string Gobo_1_Rotation {
			get {
				return ResourceManager.GetString("Gobo 1 Rotation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Gobo 2 Rotation.
		/// </summary>
		public static string Gobo_2_Rotation {
			get {
				return ResourceManager.GetString("Gobo 2 Rotation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.
		/// </summary>
		public static string GUI {
			get {
				return ResourceManager.GetString("GUI", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Colorpicker.
		/// </summary>
		public static string GUI_Colorpicker {
			get {
				return ResourceManager.GetString("GUI.Colorpicker", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Device address.
		/// </summary>
		public static string GUI_DeviceAddress {
			get {
				return ResourceManager.GetString("GUI.DeviceAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Device image.
		/// </summary>
		public static string GUI_DeviceImage {
			get {
				return ResourceManager.GetString("GUI.DeviceImage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Device name.
		/// </summary>
		public static string GUI_DeviceName {
			get {
				return ResourceManager.GetString("GUI.DeviceName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Dipswitch.
		/// </summary>
		public static string GUI_Dipswitch {
			get {
				return ResourceManager.GetString("GUI.Dipswitch", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Fadetime checkbox.
		/// </summary>
		public static string GUI_FadetimeCheckbox {
			get {
				return ResourceManager.GetString("GUI.FadetimeCheckbox", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Fadetime edit.
		/// </summary>
		public static string GUI_FadetimeEdit {
			get {
				return ResourceManager.GetString("GUI.FadetimeEdit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Position.
		/// </summary>
		public static string GUI_Position {
			get {
				return ResourceManager.GetString("GUI.Position", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Preset selector.
		/// </summary>
		public static string GUI_PresetSelector {
			get {
				return ResourceManager.GetString("GUI.PresetSelector", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Button.
		/// </summary>
		public static string GUIEditor_AddButton {
			get {
				return ResourceManager.GetString("GUIEditor.AddButton", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Colorpicker.
		/// </summary>
		public static string GUIEditor_AddColorpicker {
			get {
				return ResourceManager.GetString("GUIEditor.AddColorpicker", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Device Address.
		/// </summary>
		public static string GUIEditor_AddDeviceAddress {
			get {
				return ResourceManager.GetString("GUIEditor.AddDeviceAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Dipswitch.
		/// </summary>
		public static string GUIEditor_AddDeviceDipswitch {
			get {
				return ResourceManager.GetString("GUIEditor.AddDeviceDipswitch", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Device Image.
		/// </summary>
		public static string GUIEditor_AddDeviceImage {
			get {
				return ResourceManager.GetString("GUIEditor.AddDeviceImage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Device Name.
		/// </summary>
		public static string GUIEditor_AddDeviceName {
			get {
				return ResourceManager.GetString("GUIEditor.AddDeviceName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Dropdown.
		/// </summary>
		public static string GUIEditor_AddDropdown {
			get {
				return ResourceManager.GetString("GUIEditor.AddDropdown", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Fadetime checkbox.
		/// </summary>
		public static string GUIEditor_AddFadetimeCheckbox {
			get {
				return ResourceManager.GetString("GUIEditor.AddFadetimeCheckbox", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Fadetime edit.
		/// </summary>
		public static string GUIEditor_AddFadetimeEdit {
			get {
				return ResourceManager.GetString("GUIEditor.AddFadetimeEdit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Label.
		/// </summary>
		public static string GUIEditor_AddLabel {
			get {
				return ResourceManager.GetString("GUIEditor.AddLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Position.
		/// </summary>
		public static string GUIEditor_AddPosition {
			get {
				return ResourceManager.GetString("GUIEditor.AddPosition", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Preset selector.
		/// </summary>
		public static string GUIEditor_AddPresetSelector {
			get {
				return ResourceManager.GetString("GUIEditor.AddPresetSelector", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Slider.
		/// </summary>
		public static string GUIEditor_AddSlider {
			get {
				return ResourceManager.GetString("GUIEditor.AddSlider", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Form.
		/// </summary>
		public static string GUIEditor_Form {
			get {
				return ResourceManager.GetString("GUIEditor.Form", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Position and Size.
		/// </summary>
		public static string GUIPropertyEditor_PositionAndSize {
			get {
				return ResourceManager.GetString("GUIPropertyEditor.PositionAndSize", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Special action.
		/// </summary>
		public static string GUIPropertyEditor_SpecialAction {
			get {
				return ResourceManager.GetString("GUIPropertyEditor.SpecialAction", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Height.
		/// </summary>
		public static string Height {
			get {
				return ResourceManager.GetString("Height", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Icon.
		/// </summary>
		public static string Icon {
			get {
				return ResourceManager.GetString("Icon", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Image.
		/// </summary>
		public static string Image {
			get {
				return ResourceManager.GetString("Image", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Init value.
		/// </summary>
		public static string InitValue {
			get {
				return ResourceManager.GetString("InitValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Insert Item.
		/// </summary>
		public static string InsertItem {
			get {
				return ResourceManager.GetString("InsertItem", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Insert Range.
		/// </summary>
		public static string InsertRange {
			get {
				return ResourceManager.GetString("InsertRange", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The installation directory of PC_DIMMER could not be found in the standard path. The selection of images will be limited..
		/// </summary>
		public static string InstallationNotFoundText {
			get {
				return ResourceManager.GetString("InstallationNotFoundText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PC_DIMMER installation not found.
		/// </summary>
		public static string InstallationNotFoundTitle {
			get {
				return ResourceManager.GetString("InstallationNotFoundTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Iris.
		/// </summary>
		public static string Iris {
			get {
				return ResourceManager.GetString("Iris", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Closed.
		/// </summary>
		public static string Iris_Closed {
			get {
				return ResourceManager.GetString("Iris.Closed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Open.
		/// </summary>
		public static string Iris_Open {
			get {
				return ResourceManager.GetString("Iris.Open", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Item.
		/// </summary>
		public static string Item {
			get {
				return ResourceManager.GetString("Item", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Label.
		/// </summary>
		public static string Label {
			get {
				return ResourceManager.GetString("Label", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Left.
		/// </summary>
		public static string Left {
			get {
				return ResourceManager.GetString("Left", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to While loading the file some warnings were generated..
		/// </summary>
		public static string LoadWarnings {
			get {
				return ResourceManager.GetString("LoadWarnings", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Max.
		/// </summary>
		public static string Max {
			get {
				return ResourceManager.GetString("Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Message.
		/// </summary>
		public static string Message {
			get {
				return ResourceManager.GetString("Message", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Min.
		/// </summary>
		public static string Min {
			get {
				return ResourceManager.GetString("Min", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string Name {
			get {
				return ResourceManager.GetString("Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New.
		/// </summary>
		public static string New {
			get {
				return ResourceManager.GetString("New", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Device.
		/// </summary>
		public static string New_Device {
			get {
				return ResourceManager.GetString("New Device", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to not named.
		/// </summary>
		public static string not_named {
			get {
				return ResourceManager.GetString("not named", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Off.
		/// </summary>
		public static string Off {
			get {
				return ResourceManager.GetString("Off", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to OK.
		/// </summary>
		public static string OK {
			get {
				return ResourceManager.GetString("OK", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Open....
		/// </summary>
		public static string Open {
			get {
				return ResourceManager.GetString("Open", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This feature is not a range feature and can only be applied to items..
		/// </summary>
		public static string PCDChannelSubset_FeatureRangeError {
			get {
				return ResourceManager.GetString("PCDChannelSubset.FeatureRangeError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to In preset &apos;{0}&apos;, line {1} is not associated to a channel..
		/// </summary>
		public static string PCDCodeWriter_FeatureLineNotAssociated {
			get {
				return ResourceManager.GetString("PCDCodeWriter.FeatureLineNotAssociated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to There are multiple sliders for channel &apos;{0}&apos;. Ignoring the latter..
		/// </summary>
		public static string PCDCodeWriter_MultipleSlidersForChannel {
			get {
				return ResourceManager.GetString("PCDCodeWriter.MultipleSlidersForChannel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This DDF was not created using PCD-DDF-in-WPF! I won&apos;t be able to load many of the details in this file..
		/// </summary>
		public static string PCDDeviceParser_UnknownGenerator {
			get {
				return ResourceManager.GetString("PCDDeviceParser.UnknownGenerator", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Use fadetime.
		/// </summary>
		public static string PCDFadetimeCheckbox_UseFadetime {
			get {
				return ResourceManager.GetString("PCDFadetimeCheckbox.UseFadetime", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range of feature &apos;{0}&apos; collides with subset &apos;{1}&apos;..
		/// </summary>
		public static string PCDFeatureParser_Collide {
			get {
				return ResourceManager.GetString("PCDFeatureParser.Collide", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Feature &apos;{0}&apos; can&apos;t be applied because another feature that should be on the same channel is on another one..
		/// </summary>
		public static string PCDFeatureWriter_DifferentChannels {
			get {
				return ResourceManager.GetString("PCDFeatureWriter.DifferentChannels", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Feature &apos;{0}&apos; was applied more than once..
		/// </summary>
		public static string PCDFeatureWriter_FeatureAppliedMoreThanOnce {
			get {
				return ResourceManager.GetString("PCDFeatureWriter.FeatureAppliedMoreThanOnce", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported yet..
		/// </summary>
		public static string PCDGUIParser_NodeTypeNotSupported {
			get {
				return ResourceManager.GetString("PCDGUIParser.NodeTypeNotSupported", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The preset &apos;{0}&apos; could not be assigned to a button because the preset&apos;s name is not valid..
		/// </summary>
		public static string PCDGUIWriter_InvalidPresetName {
			get {
				return ResourceManager.GetString("PCDGUIWriter.InvalidPresetName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to On preset &apos;{0}&apos; an item was not associated to a channel..
		/// </summary>
		public static string PCDPresetWriter_PresetItemNotAssociated {
			get {
				return ResourceManager.GetString("PCDPresetWriter.PresetItemNotAssociated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Portable Network Graphic.
		/// </summary>
		public static string PngImage {
			get {
				return ResourceManager.GetString("PngImage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Preset.
		/// </summary>
		public static string Preset {
			get {
				return ResourceManager.GetString("Preset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Preset channel.
		/// </summary>
		public static string PresetChannel {
			get {
				return ResourceManager.GetString("PresetChannel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Channel.
		/// </summary>
		public static string PresetEditor_AddChannel {
			get {
				return ResourceManager.GetString("PresetEditor.AddChannel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add Preset.
		/// </summary>
		public static string PresetEditor_AddPreset {
			get {
				return ResourceManager.GetString("PresetEditor.AddPreset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Clone Preset.
		/// </summary>
		public static string PresetEditor_ClonePreset {
			get {
				return ResourceManager.GetString("PresetEditor.ClonePreset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Presets.
		/// </summary>
		public static string Presets {
			get {
				return ResourceManager.GetString("Presets", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Prisma.
		/// </summary>
		public static string Prisma {
			get {
				return ResourceManager.GetString("Prisma", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Prisma Rotation.
		/// </summary>
		public static string Prisma_Rotation {
			get {
				return ResourceManager.GetString("Prisma Rotation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Join with next item.
		/// </summary>
		public static string PropertyEditor_Joinwithnextitem {
			get {
				return ResourceManager.GetString("PropertyEditor.Joinwithnextitem", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range.
		/// </summary>
		public static string Range {
			get {
				return ResourceManager.GetString("Range", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Left Max-Min.
		/// </summary>
		public static string Range_Left_Max_Min {
			get {
				return ResourceManager.GetString("Range Left Max-Min", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Left Min-Max.
		/// </summary>
		public static string Range_Left_Min_Max {
			get {
				return ResourceManager.GetString("Range Left Min-Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Min-Max.
		/// </summary>
		public static string Range_Min_Max {
			get {
				return ResourceManager.GetString("Range Min-Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Off-Max.
		/// </summary>
		public static string Range_Off_Max {
			get {
				return ResourceManager.GetString("Range Off-Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Right Max-Min.
		/// </summary>
		public static string Range_Right_Max_Min {
			get {
				return ResourceManager.GetString("Range Right Max-Min", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Right Min-Max.
		/// </summary>
		public static string Range_Right_Min_Max {
			get {
				return ResourceManager.GetString("Range Right Min-Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Remove.
		/// </summary>
		public static string Remove {
			get {
				return ResourceManager.GetString("Remove", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save....
		/// </summary>
		public static string Save {
			get {
				return ResourceManager.GetString("Save", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Do you want to save the file?.
		/// </summary>
		public static string SaveQuestionText {
			get {
				return ResourceManager.GetString("SaveQuestionText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to File modified.
		/// </summary>
		public static string SaveQuestionTitle {
			get {
				return ResourceManager.GetString("SaveQuestionTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to While saving the file the following warnings were generated..
		/// </summary>
		public static string SaveWarnings {
			get {
				return ResourceManager.GetString("SaveWarnings", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Set value.
		/// </summary>
		public static string SetValue {
			get {
				return ResourceManager.GetString("SetValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Shutter.
		/// </summary>
		public static string Shutter {
			get {
				return ResourceManager.GetString("Shutter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Closed.
		/// </summary>
		public static string Shutter_Closed {
			get {
				return ResourceManager.GetString("Shutter.Closed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Open.
		/// </summary>
		public static string Shutter_Open {
			get {
				return ResourceManager.GetString("Shutter.Open", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Single.
		/// </summary>
		public static string Single {
			get {
				return ResourceManager.GetString("Single", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Strobe.
		/// </summary>
		public static string Strobe {
			get {
				return ResourceManager.GetString("Strobe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Subset.
		/// </summary>
		public static string Subset {
			get {
				return ResourceManager.GetString("Subset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The element selected needs to have space for the new element..
		/// </summary>
		public static string TheElementSelectedNeedsToHaveSpaceForTheNewElement {
			get {
				return ResourceManager.GetString("TheElementSelectedNeedsToHaveSpaceForTheNewElement", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Top.
		/// </summary>
		public static string Top {
			get {
				return ResourceManager.GetString("Top", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Triple.
		/// </summary>
		public static string Triple {
			get {
				return ResourceManager.GetString("Triple", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Up.
		/// </summary>
		public static string Up {
			get {
				return ResourceManager.GetString("Up", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value.
		/// </summary>
		public static string Value {
			get {
				return ResourceManager.GetString("Value", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vendor.
		/// </summary>
		public static string Vendor {
			get {
				return ResourceManager.GetString("Vendor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Width.
		/// </summary>
		public static string Width {
			get {
				return ResourceManager.GetString("Width", resourceCulture);
			}
		}
	}
}
