//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koinzer.pcdddfinwpf {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Koinzer.pcdddfinwpf.Strings", typeof(Strings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;Not named&gt;.
		/// </summary>
		public static string _Not_named_ {
			get {
				return ResourceManager.GetString("<Not named>", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to About.
		/// </summary>
		public static string About {
			get {
				return ResourceManager.GetString("About", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AddChannel.
		/// </summary>
		public static string AddChannel {
			get {
				return ResourceManager.GetString("AddChannel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AddItem.
		/// </summary>
		public static string AddItem {
			get {
				return ResourceManager.GetString("AddItem", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AddRange.
		/// </summary>
		public static string AddRange {
			get {
				return ResourceManager.GetString("AddRange", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AllFiles.
		/// </summary>
		public static string AllFiles {
			get {
				return ResourceManager.GetString("AllFiles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Amber.
		/// </summary>
		public static string Amber {
			get {
				return ResourceManager.GetString("Amber", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Author.
		/// </summary>
		public static string Author {
			get {
				return ResourceManager.GetString("Author", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Caption.
		/// </summary>
		public static string Caption {
			get {
				return ResourceManager.GetString("Caption", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Channel.
		/// </summary>
		public static string Channel {
			get {
				return ResourceManager.GetString("Channel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Channels.
		/// </summary>
		public static string Channels {
			get {
				return ResourceManager.GetString("Channels", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ChannelType.
		/// </summary>
		public static string ChannelType {
			get {
				return ResourceManager.GetString("ChannelType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Checked.
		/// </summary>
		public static string Checked {
			get {
				return ResourceManager.GetString("Checked", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Color.
		/// </summary>
		public static string Color {
			get {
				return ResourceManager.GetString("Color", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Control.
		/// </summary>
		public static string Control {
			get {
				return ResourceManager.GetString("Control", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		public static string Description {
			get {
				return ResourceManager.GetString("Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Device.
		/// </summary>
		public static string Device {
			get {
				return ResourceManager.GetString("Device", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to DeviceAmberEditor.AmberGFactor.
		/// </summary>
		public static string DeviceAmberEditor_AmberGFactor {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.AmberGFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to DeviceAmberEditor.AmberRFactor.
		/// </summary>
		public static string DeviceAmberEditor_AmberRFactor {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.AmberRFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to DeviceAmberEditor.CompensateB.
		/// </summary>
		public static string DeviceAmberEditor_CompensateB {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.CompensateB", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to DeviceAmberEditor.CompensateRG.
		/// </summary>
		public static string DeviceAmberEditor_CompensateRG {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.CompensateRG", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to DeviceAmberEditor.UseAmbermixing.
		/// </summary>
		public static string DeviceAmberEditor_UseAmbermixing {
			get {
				return ResourceManager.GetString("DeviceAmberEditor.UseAmbermixing", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Dimmer.
		/// </summary>
		public static string Dimmer {
			get {
				return ResourceManager.GetString("Dimmer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Down.
		/// </summary>
		public static string Down {
			get {
				return ResourceManager.GetString("Down", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Dropdown.
		/// </summary>
		public static string Dropdown {
			get {
				return ResourceManager.GetString("Dropdown", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ExceptionWindow.ExceptionTextHeader.
		/// </summary>
		public static string ExceptionWindow_ExceptionTextHeader {
			get {
				return ResourceManager.GetString("ExceptionWindow.ExceptionTextHeader", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ExceptionWindow.Message.
		/// </summary>
		public static string ExceptionWindow_Message {
			get {
				return ResourceManager.GetString("ExceptionWindow.Message", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ExceptionWindow.MessageHeader.
		/// </summary>
		public static string ExceptionWindow_MessageHeader {
			get {
				return ResourceManager.GetString("ExceptionWindow.MessageHeader", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Fade.
		/// </summary>
		public static string Fade {
			get {
				return ResourceManager.GetString("Fade", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FadeTimeMs.
		/// </summary>
		public static string FadeTimeMs {
			get {
				return ResourceManager.GetString("FadeTimeMs", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Features.
		/// </summary>
		public static string Features {
			get {
				return ResourceManager.GetString("Features", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This feature is not a range and can only be applied to items..
		/// </summary>
		public static string FeatureSelector_FeatureRangeErrorText {
			get {
				return ResourceManager.GetString("FeatureSelector.FeatureRangeErrorText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error adding feature.
		/// </summary>
		public static string FeatureSelector_FeatureRangeErrorTitle {
			get {
				return ResourceManager.GetString("FeatureSelector.FeatureRangeErrorTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FileCouldNotBeLoaded.
		/// </summary>
		public static string FileCouldNotBeLoaded {
			get {
				return ResourceManager.GetString("FileCouldNotBeLoaded", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FileCouldNotBeSaved.
		/// </summary>
		public static string FileCouldNotBeSaved {
			get {
				return ResourceManager.GetString("FileCouldNotBeSaved", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Gobo 1 Rotation.
		/// </summary>
		public static string Gobo_1_Rotation {
			get {
				return ResourceManager.GetString("Gobo 1 Rotation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Gobo 2 Rotation.
		/// </summary>
		public static string Gobo_2_Rotation {
			get {
				return ResourceManager.GetString("Gobo 2 Rotation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.
		/// </summary>
		public static string GUI {
			get {
				return ResourceManager.GetString("GUI", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.Colorpicker.
		/// </summary>
		public static string GUI_Colorpicker {
			get {
				return ResourceManager.GetString("GUI.Colorpicker", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.DeviceAddress.
		/// </summary>
		public static string GUI_DeviceAddress {
			get {
				return ResourceManager.GetString("GUI.DeviceAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.DeviceImage.
		/// </summary>
		public static string GUI_DeviceImage {
			get {
				return ResourceManager.GetString("GUI.DeviceImage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.DeviceName.
		/// </summary>
		public static string GUI_DeviceName {
			get {
				return ResourceManager.GetString("GUI.DeviceName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.Dipswitch.
		/// </summary>
		public static string GUI_Dipswitch {
			get {
				return ResourceManager.GetString("GUI.Dipswitch", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.FadetimeCheckbox.
		/// </summary>
		public static string GUI_FadetimeCheckbox {
			get {
				return ResourceManager.GetString("GUI.FadetimeCheckbox", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.FadetimeEdit.
		/// </summary>
		public static string GUI_FadetimeEdit {
			get {
				return ResourceManager.GetString("GUI.FadetimeEdit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.Position.
		/// </summary>
		public static string GUI_Position {
			get {
				return ResourceManager.GetString("GUI.Position", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUI.PresetSelector.
		/// </summary>
		public static string GUI_PresetSelector {
			get {
				return ResourceManager.GetString("GUI.PresetSelector", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddButton.
		/// </summary>
		public static string GUIEditor_AddButton {
			get {
				return ResourceManager.GetString("GUIEditor.AddButton", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddColorpicker.
		/// </summary>
		public static string GUIEditor_AddColorpicker {
			get {
				return ResourceManager.GetString("GUIEditor.AddColorpicker", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddDeviceAddress.
		/// </summary>
		public static string GUIEditor_AddDeviceAddress {
			get {
				return ResourceManager.GetString("GUIEditor.AddDeviceAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddDeviceDipswitch.
		/// </summary>
		public static string GUIEditor_AddDeviceDipswitch {
			get {
				return ResourceManager.GetString("GUIEditor.AddDeviceDipswitch", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddDeviceImage.
		/// </summary>
		public static string GUIEditor_AddDeviceImage {
			get {
				return ResourceManager.GetString("GUIEditor.AddDeviceImage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddDeviceName.
		/// </summary>
		public static string GUIEditor_AddDeviceName {
			get {
				return ResourceManager.GetString("GUIEditor.AddDeviceName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddDropdown.
		/// </summary>
		public static string GUIEditor_AddDropdown {
			get {
				return ResourceManager.GetString("GUIEditor.AddDropdown", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddFadetimeCheckbox.
		/// </summary>
		public static string GUIEditor_AddFadetimeCheckbox {
			get {
				return ResourceManager.GetString("GUIEditor.AddFadetimeCheckbox", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddFadetimeEdit.
		/// </summary>
		public static string GUIEditor_AddFadetimeEdit {
			get {
				return ResourceManager.GetString("GUIEditor.AddFadetimeEdit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddLabel.
		/// </summary>
		public static string GUIEditor_AddLabel {
			get {
				return ResourceManager.GetString("GUIEditor.AddLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddPosition.
		/// </summary>
		public static string GUIEditor_AddPosition {
			get {
				return ResourceManager.GetString("GUIEditor.AddPosition", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddPresetSelector.
		/// </summary>
		public static string GUIEditor_AddPresetSelector {
			get {
				return ResourceManager.GetString("GUIEditor.AddPresetSelector", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIEditor.AddSlider.
		/// </summary>
		public static string GUIEditor_AddSlider {
			get {
				return ResourceManager.GetString("GUIEditor.AddSlider", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIPropertyEditor.PositionAndSize.
		/// </summary>
		public static string GUIPropertyEditor_PositionAndSize {
			get {
				return ResourceManager.GetString("GUIPropertyEditor.PositionAndSize", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to GUIPropertyEditor.SpecialAction.
		/// </summary>
		public static string GUIPropertyEditor_SpecialAction {
			get {
				return ResourceManager.GetString("GUIPropertyEditor.SpecialAction", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Height.
		/// </summary>
		public static string Height {
			get {
				return ResourceManager.GetString("Height", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Icon.
		/// </summary>
		public static string Icon {
			get {
				return ResourceManager.GetString("Icon", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Image.
		/// </summary>
		public static string Image {
			get {
				return ResourceManager.GetString("Image", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to InitValue.
		/// </summary>
		public static string InitValue {
			get {
				return ResourceManager.GetString("InitValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to InsertItem.
		/// </summary>
		public static string InsertItem {
			get {
				return ResourceManager.GetString("InsertItem", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to InsertRange.
		/// </summary>
		public static string InsertRange {
			get {
				return ResourceManager.GetString("InsertRange", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to InstallationNotFoundText.
		/// </summary>
		public static string InstallationNotFoundText {
			get {
				return ResourceManager.GetString("InstallationNotFoundText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to InstallationNotFoundTitle.
		/// </summary>
		public static string InstallationNotFoundTitle {
			get {
				return ResourceManager.GetString("InstallationNotFoundTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Iris.
		/// </summary>
		public static string Iris {
			get {
				return ResourceManager.GetString("Iris", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Iris.Closed.
		/// </summary>
		public static string Iris_Closed {
			get {
				return ResourceManager.GetString("Iris.Closed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Iris.Open.
		/// </summary>
		public static string Iris_Open {
			get {
				return ResourceManager.GetString("Iris.Open", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Item.
		/// </summary>
		public static string Item {
			get {
				return ResourceManager.GetString("Item", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Left.
		/// </summary>
		public static string Left {
			get {
				return ResourceManager.GetString("Left", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Libraries.
		/// </summary>
		public static string Libraries {
			get {
				return ResourceManager.GetString("Libraries", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to License.
		/// </summary>
		public static string License {
			get {
				return ResourceManager.GetString("License", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to LoadWarnings.
		/// </summary>
		public static string LoadWarnings {
			get {
				return ResourceManager.GetString("LoadWarnings", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Max.
		/// </summary>
		public static string Max {
			get {
				return ResourceManager.GetString("Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Message.
		/// </summary>
		public static string Message {
			get {
				return ResourceManager.GetString("Message", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Min.
		/// </summary>
		public static string Min {
			get {
				return ResourceManager.GetString("Min", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string Name {
			get {
				return ResourceManager.GetString("Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New.
		/// </summary>
		public static string New {
			get {
				return ResourceManager.GetString("New", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Device.
		/// </summary>
		public static string New_Device {
			get {
				return ResourceManager.GetString("New Device", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Off.
		/// </summary>
		public static string Off {
			get {
				return ResourceManager.GetString("Off", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to OK.
		/// </summary>
		public static string OK {
			get {
				return ResourceManager.GetString("OK", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Open....
		/// </summary>
		public static string Open {
			get {
				return ResourceManager.GetString("Open", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This feature is not a range and can only be applied to items..
		/// </summary>
		public static string PCDChannelSubset_FeatureRangeError {
			get {
				return ResourceManager.GetString("PCDChannelSubset.FeatureRangeError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to In preset &apos;{0}&apos;, line {1} is not associated to a channel..
		/// </summary>
		public static string PCDCodeWriter_FeatureLineNotAssociated {
			get {
				return ResourceManager.GetString("PCDCodeWriter.FeatureLineNotAssociated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to There are multiple sliders for channel &apos;{0}&apos;. Ignoring the latter..
		/// </summary>
		public static string PCDCodeWriter_MultipleSlidersForChannel {
			get {
				return ResourceManager.GetString("PCDCodeWriter.MultipleSlidersForChannel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This DDF was not created using PCD-DDF-in-WPF! I won&apos;t be able to load many of the details in this file..
		/// </summary>
		public static string PCDDeviceParser_UnknownGenerator {
			get {
				return ResourceManager.GetString("PCDDeviceParser.UnknownGenerator", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PCDFadetimeCheckbox.UseFadetime.
		/// </summary>
		public static string PCDFadetimeCheckbox_UseFadetime {
			get {
				return ResourceManager.GetString("PCDFadetimeCheckbox.UseFadetime", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Featurerange of feature &apos;{0}&apos; collides with subset &apos;{1}&apos;..
		/// </summary>
		public static string PCDFeatureParser_Collide {
			get {
				return ResourceManager.GetString("PCDFeatureParser.Collide", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Feature &apos;{0}&apos; can&apos;t be applied because another feature that should be on the same channel is on another one..
		/// </summary>
		public static string PCDFeatureWriter_DifferentChannels {
			get {
				return ResourceManager.GetString("PCDFeatureWriter.DifferentChannels", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Feature &apos;{0}&apos; was applied more than once..
		/// </summary>
		public static string PCDFeatureWriter_FeatureAppliedMoreThanOnce {
			get {
				return ResourceManager.GetString("PCDFeatureWriter.FeatureAppliedMoreThanOnce", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported yet..
		/// </summary>
		public static string PCDGUIParser_NodeTypeNotSupported {
			get {
				return ResourceManager.GetString("PCDGUIParser.NodeTypeNotSupported", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The preset &apos;{0}&apos; could not be assigned to a button because the preset&apos;s name is not valid..
		/// </summary>
		public static string PCDGUIWriter_InvalidPresetName {
			get {
				return ResourceManager.GetString("PCDGUIWriter.InvalidPresetName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PCDPresetWriter.PresetItemNotAssociated.
		/// </summary>
		public static string PCDPresetWriter_PresetItemNotAssociated {
			get {
				return ResourceManager.GetString("PCDPresetWriter.PresetItemNotAssociated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PngImage.
		/// </summary>
		public static string PngImage {
			get {
				return ResourceManager.GetString("PngImage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Preset.
		/// </summary>
		public static string Preset {
			get {
				return ResourceManager.GetString("Preset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PresetChannel.
		/// </summary>
		public static string PresetChannel {
			get {
				return ResourceManager.GetString("PresetChannel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PresetEditor.Add Channel.
		/// </summary>
		public static string PresetEditor_Add_Channel {
			get {
				return ResourceManager.GetString("PresetEditor.Add Channel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PresetEditor.AddPreset.
		/// </summary>
		public static string PresetEditor_AddPreset {
			get {
				return ResourceManager.GetString("PresetEditor.AddPreset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PresetEditor.ClonePreset.
		/// </summary>
		public static string PresetEditor_ClonePreset {
			get {
				return ResourceManager.GetString("PresetEditor.ClonePreset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Presets.
		/// </summary>
		public static string Presets {
			get {
				return ResourceManager.GetString("Presets", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Prisma.
		/// </summary>
		public static string Prisma {
			get {
				return ResourceManager.GetString("Prisma", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Prisma Rotation.
		/// </summary>
		public static string Prisma_Rotation {
			get {
				return ResourceManager.GetString("Prisma Rotation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PropertyEditor.Joinwithnextitem.
		/// </summary>
		public static string PropertyEditor_Joinwithnextitem {
			get {
				return ResourceManager.GetString("PropertyEditor.Joinwithnextitem", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range.
		/// </summary>
		public static string Range {
			get {
				return ResourceManager.GetString("Range", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Left Min-Max.
		/// </summary>
		public static string Range_Left_Min_Max {
			get {
				return ResourceManager.GetString("Range Left Min-Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Min-Max.
		/// </summary>
		public static string Range_Min_Max {
			get {
				return ResourceManager.GetString("Range Min-Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Off-Max.
		/// </summary>
		public static string Range_Off_Max {
			get {
				return ResourceManager.GetString("Range Off-Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Range Right Min-Max.
		/// </summary>
		public static string Range_Right_Min_Max {
			get {
				return ResourceManager.GetString("Range Right Min-Max", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Remove.
		/// </summary>
		public static string Remove {
			get {
				return ResourceManager.GetString("Remove", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save....
		/// </summary>
		public static string Save {
			get {
				return ResourceManager.GetString("Save", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SaveQuestionText.
		/// </summary>
		public static string SaveQuestionText {
			get {
				return ResourceManager.GetString("SaveQuestionText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SaveQuestionTitle.
		/// </summary>
		public static string SaveQuestionTitle {
			get {
				return ResourceManager.GetString("SaveQuestionTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SaveWarnings.
		/// </summary>
		public static string SaveWarnings {
			get {
				return ResourceManager.GetString("SaveWarnings", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SetValue.
		/// </summary>
		public static string SetValue {
			get {
				return ResourceManager.GetString("SetValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Shutter.
		/// </summary>
		public static string Shutter {
			get {
				return ResourceManager.GetString("Shutter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Shutter.Closed.
		/// </summary>
		public static string Shutter_Closed {
			get {
				return ResourceManager.GetString("Shutter.Closed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Shutter.Open.
		/// </summary>
		public static string Shutter_Open {
			get {
				return ResourceManager.GetString("Shutter.Open", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Single.
		/// </summary>
		public static string Single {
			get {
				return ResourceManager.GetString("Single", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Strobe.
		/// </summary>
		public static string Strobe {
			get {
				return ResourceManager.GetString("Strobe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Subset.
		/// </summary>
		public static string Subset {
			get {
				return ResourceManager.GetString("Subset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to TheElementSelectedNeedsToHaveSpaceForTheNewElement.
		/// </summary>
		public static string TheElementSelectedNeedsToHaveSpaceForTheNewElement {
			get {
				return ResourceManager.GetString("TheElementSelectedNeedsToHaveSpaceForTheNewElement", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Top.
		/// </summary>
		public static string Top {
			get {
				return ResourceManager.GetString("Top", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Triple.
		/// </summary>
		public static string Triple {
			get {
				return ResourceManager.GetString("Triple", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Up.
		/// </summary>
		public static string Up {
			get {
				return ResourceManager.GetString("Up", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value.
		/// </summary>
		public static string Value {
			get {
				return ResourceManager.GetString("Value", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vendor.
		/// </summary>
		public static string Vendor {
			get {
				return ResourceManager.GetString("Vendor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Width.
		/// </summary>
		public static string Width {
			get {
				return ResourceManager.GetString("Width", resourceCulture);
			}
		}
	}
}
